//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASPNetRolesPermisos
    {
        public int IdModulo { get; set; }
        public string Id { get; set; }
        public Nullable<bool> Entrar { get; set; }
        public Nullable<bool> Grabar { get; set; }
        public Nullable<bool> Editar { get; set; }
        public Nullable<bool> Eliminar { get; set; }
        public Nullable<bool> Anular { get; set; }
        public Nullable<bool> Consultar { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
    
        public virtual ASPNetModulos ASPNetModulos { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
    }
}
