//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bodegas
    {
        public string bodega { get; set; }
        public string nombre { get; set; }
        public string cuentacontable { get; set; }
        public string CENTROCOSTOS { get; set; }
        public string NUMEROMAQUINA { get; set; }
        public Nullable<decimal> DIAS { get; set; }
        public string CODIGORETEICA { get; set; }
        public string DIRECCIONBODEGA { get; set; }
        public string TELEFONOBODEGA { get; set; }
        public string FAXBODEGA { get; set; }
    }
}
