//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidosc1W_2000
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidosc1W_2000()
        {
            this.pedidosc2W_2000 = new HashSet<pedidosc2W_2000>();
        }
    
        public string numero { get; set; }
        public string mes { get; set; }
        public System.DateTime fecha { get; set; }
        public int anulado { get; set; }
        public System.DateTime fechaDespacho { get; set; }
        public string nit { get; set; }
        public string vendedor { get; set; }
        public decimal iva { get; set; }
        public decimal valor { get; set; }
        public decimal descuento { get; set; }
        public Nullable<bool> estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string ZONA { get; set; }
        public string prefijo { get; set; }
        public string contacto { get; set; }
        public string BODEGA { get; set; }
        public string OBSERVACIONES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidosc2W_2000> pedidosc2W_2000 { get; set; }
    }
}
