//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrazabilidadPedidos
    {
        public int IdTrazabilidad { get; set; }
        public string NumeroPedido { get; set; }
        public Nullable<System.DateTime> FechaDespacho { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string NumeroGuia { get; set; }
        public int IdTransportadora { get; set; }
        public string LinkSeguimiento { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
    
        public virtual tbl_Transportadoras tbl_Transportadoras { get; set; }
    }
}
