//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CCostosCompradores
    {
        public int IdCentroCostos { get; set; }
        public string DescripcionCentroCostos { get; set; }
        public decimal ValorPresupuesto { get; set; }
        public string Cedula { get; set; }
    }
}
