//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendedor
    {
        public string vendedor1 { get; set; }
        public string nombre { get; set; }
        public string cedula { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public decimal comision { get; set; }
        public decimal recaudo_0 { get; set; }
        public decimal recaudo_30 { get; set; }
        public decimal recaudo_60 { get; set; }
        public decimal recaudo_90 { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string LOCALIZACION { get; set; }
        public string CLASIFICACION { get; set; }
        public string PERSONA { get; set; }
        public string SEXO { get; set; }
        public string CATEGORIA { get; set; }
        public string ZONA { get; set; }
        public string LCINCUENTAYOCHO { get; set; }
        public string VENDEDORINT { get; set; }
        public string BODEGA { get; set; }
        public Nullable<decimal> TIPOVENDEDOR { get; set; }
        public Nullable<int> COMERCIO { get; set; }
        public string NOMBREVENDEDOR { get; set; }
        public Nullable<int> PUNTODEVENTA { get; set; }
        public Nullable<int> GRUPOVENDEDOR { get; set; }
        public Nullable<int> GRUPOSANTANDER { get; set; }
        public Nullable<int> EXTERNOTELEMERCADEO { get; set; }
        public string OBSERVACION { get; set; }
        public string BANDERA { get; set; }
        public Nullable<int> COMISIONPORZONA { get; set; }
        public Nullable<int> COPIAS { get; set; }
        public Nullable<int> EXCLUIRVENDEDOROH { get; set; }
        public string CONTRASEÑA { get; set; }
        public string CODIGOIND { get; set; }
        public string CORREODELVENDEDOR { get; set; }
        public string CELULAR { get; set; }
    }
}
